# Multi-arch: amd64,arm64
apiVersion: batch/v1
kind: Job
metadata:
  name: weekly-habit-stats-test
  namespace: me
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    spec:
      containers:
      - args:
        - main.py
        - habits
        - --update
        - --days
        - "90"
        envFrom:
        - secretRef:
            name: app-secret
        image: 113745426946.dkr.ecr.us-east-1.amazonaws.com/xuetaotest/me-task:latest
        imagePullPolicy: Always
        name: habit-stats
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30