apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-summary
  labels:
    app: me-analytics
spec:
  schedule: "0 1 * * *"  # 每天凌晨1点执行
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-summary
            image: ghcr.io/magicsong/me-tasks:latest  # 替换为您的镜像仓库地址
            args:
            - summary
            - daily
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "200m"
                memory: "256Mi"
            envFrom:
            - secretRef:
                name: me-app-secrets  # 确保包含数据库连接信息的Secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekly-summary
  labels:
    app: me-analytics
spec:
  schedule: "0 2 * * 0"  # 每周日凌晨2点执行
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: weekly-summary
            image: ghcr.io/magicsong/me-tasks:latest  # 替换为您的镜像仓库地址
            args:
            - summary
            - weekly
            - --days
            - "7"
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "200m"
                memory: "256Mi"
            envFrom:
            - secretRef:
                name: me-app-secrets  # 确保包含数据库连接信息的Secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: monthly-summary
  labels:
    app: me-analytics
spec:
  schedule: "0 3 1 * *"  # 每月1日凌晨3点执行
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: monthly-summary
            image: ghcr.io/magicsong/me-tasks:latest  # 替换为您的镜像仓库地址
            args:
            - summary
            - monthly
            - --days
            - "30"
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "200m"
                memory: "256Mi"
            envFrom:
            - secretRef:
                name: me-app-secrets  # 确保包含数据库连接信息的Secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekly-charts
  labels:
    app: me-analytics
spec:
  schedule: "0 4 * * 0"  # 每周日凌晨4点执行
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: weekly-charts
            image: ghcr.io/magicsong/me-tasks:latest  # 替换为您的镜像仓库地址
            args:
            - charts
            - --days
            - "7"
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "200m"
                memory: "256Mi"
            envFrom:
            - secretRef:
                name: me-app-secrets  # 确保包含数据库连接信息的Secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: monthly-charts
  labels:
    app: me-analytics
spec:
  schedule: "0 5 1 * *"  # 每月1日凌晨5点执行
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: monthly-charts
            image: ghcr.io/magicsong/me-tasks:latest  # 替换为您的镜像仓库地址
            args:
            - charts
            - --days
            - "30"
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "200m"
                memory: "256Mi"
            envFrom:
            - secretRef:
                name: me-app-secrets  # 确保包含数据库连接信息的Secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: export-to-s3
  labels:
    app: me-analytics
spec:
  schedule: "0 6 * * 0"  # 每周日凌晨6点执行
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: export-to-s3
            image: ghcr.io/magicsong/me-tasks:latest  # 替换为您的镜像仓库地址
            args:
            - export
            - --bucket
            - me-analytics-data
            - --prefix
            - analytics
            - --date-prefix
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "200m"
                memory: "256Mi"
            envFrom:
            - secretRef:
                name: me-app-secrets  # 确保包含数据库连接信息和AWS凭证
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-habit-stats
  labels:
    app: me-analytics
spec:
  schedule: "30 1 * * *"  # 每天凌晨1点30执行
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: habit-stats
            image: ghcr.io/magicsong/me-tasks:latest  # 替换为您的镜像仓库地址
            args:
            - habits
            - "${USER_ID}"  # 从环境变量中获取用户ID
            - --days
            - "30"
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "200m"
                memory: "256Mi"
            envFrom:
            - secretRef:
                name: me-app-secrets  # 确保包含数据库连接信息和用户ID
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekly-habit-stats
  labels:
    app: me-analytics
spec:
  schedule: "0 3 * * 0"  # 每周日凌晨3点执行
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: habit-stats
            image: ghcr.io/magicsong/me-tasks:latest  # 替换为您的镜像仓库地址
            args:
            - habits
            - "${USER_ID}"  # 从环境变量中获取用户ID
            - --days
            - "90"
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "200m"
                memory: "256Mi"
            envFrom:
            - secretRef:
                name: me-app-secrets  # 确保包含数据库连接信息和用户ID
          restartPolicy: OnFailure
