apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  nextauth-url: "http://xx"  # 替换为您的实际 URL
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  POSTGRES_URL:   "" # base64 编码的 secret 值
  NEXTAUTH_URL:   "" # base64 编码的数据库连接字符串
  AUTH_GITHUB_ID: ""
  AUTH_GITHUB_SECRET: ""
  AUTH_SECRET: ""