apiVersion: apps/v1
kind: Deployment
metadata:
  name: me-app
  labels:
    app: me-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: me-app
  template:
    metadata:
      labels:
        app: me-app
    spec:
      containers:
      - name: me-app
        image: ghcr.io/magicsong/magicsong-app:latest  # 使用您的镜像仓库地址替换这里
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: url

---
apiVersion: v1
kind: Service
metadata:
  name: me-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: me-app
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
